# Games.toml example
# Specifies just the devtest

[devtest]
name = "Developer Test"
path = ":"
texture_path = "img"
blockdefs = "example/palette_internal.toml"
entdefs = "example/example_entities.toml"
working_dir = ""
file = ""

[devtest_two]
name = "Developer Test Two"
path = ":"
texture_path = "img"
blockdefs = "example/palette_two.toml"
entdefs = "example/example_entities.toml"
working_dir = ""
file = ""